
#include "sorth-runtime.h"



// This function will be generated by the compiler.
extern "C" int script_top_level();


int main(int argc, char* argv[])
{
    // Assume we'll be successful.
    int result = EXIT_SUCCESS;

    try
    {
        // Initialize the data stack, and  make sure that the command line arguments are available
        // to the Forth program.
        stack_initialize();

        sorth::run_time::abi::words::register_command_line_arguments(argc, argv);

        // Call the generated top level of the user code, and report any errors that were raised by
        // the user code, if any.
        result = script_top_level();
    }
    catch (const std::exception& error)
    {
        // Something went wrong in the C++ run-time code.  Report the error and return a failure
        // status to the OS.
        std::cerr << "An unexpected error occurred: " << std::endl
                  << error.what() << std::endl;

        result = EXIT_FAILURE;
    }

    // Return the result of the script execution to the OS.
    return result;
}
