
#include <iostream>
#include <exception>



// This function is generated by the Strainge Forth compiler.
extern "C" unsigned char script_top_level(void);


// This function is defined in sorth-runtime.lib.
extern "C" void stack_initialize();


// This function is also defined in sorth-runtime.lib.
namespace sorth::run_time::abi::words
{
    void register_command_line_arguments(int argc, char* argv[]);
}


int main(int argc, char* argv[])
{
    // Assume we'll be successful.
    int result = EXIT_SUCCESS;

    try
    {
        // Initialize the data stack, and  make sure that the command line arguments are available
        // to the Forth program.
        stack_initialize();

        sorth::run_time::abi::words::register_command_line_arguments(argc, argv);

        // Call the generated top level of the user code, and report any errors that were raised by
        // the user code, if any.
        result = script_top_level();
    }
    catch (const std::exception& error)
    {
        // Something went wrong in the C++ run-time code.  Report the error and return a failure
        // status to the OS.
        std::cerr << "An unexpected error occurred: " << std::endl
                  << error.what() << std::endl;

        result = EXIT_FAILURE;
    }

    // Return the result of the script execution to the OS.
    return result;
}
